/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/public class AgregarEstudiante extends javax.swing.JFrame {
  ListaRegistroEstudiante RegEst = new  ListaRegistroEstudiante() ;
    
   Estudiante EstudianteActual = new Estudiante();
    /** Creates new form AgregarEstudiante */
    public AgregarEstudiante() {
        initComponents();
    }
     public AgregarEstudiante( ListaRegistroEstudiante E) {
        initComponents();
        this.RegEst = E;}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotonOK = new javax.swing.JButton();
        CedulaTxt = new javax.swing.JTextField();
        NombresTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        BotonImprimir = new javax.swing.JButton();
        jButton1.setText("jButton1");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setText("Cédula");
        
        jLabel2.setText("Nombre y Apellido");
        
        jLabel3.setText("Correo Electrónico");
        
        BotonOK.setText("OK");
    }
    
}
